services:
  - type: web
    name: shenghuozhiyan
    env: python
    buildCommand: pip install -r requirements.txt && python fix_render_modules.py
    startCommand: gunicorn render_fix:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
