services:
  - type: web
    name: daoyizhiyan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
