services:
  - type: web
    name: daoyizhiyan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000 